services:
  - type: web
    name: procureiq-springboot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: procureiq-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: procureiq-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: procureiq-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: "86400000"
      - key: OTEL_SDK_DISABLED
        value: "true"

databases:
  - name: procureiq-db
    plan: free
    databaseName: procureiq
    user: procureiq_user
